import fs from 'fs';
import path from 'path';
import { exec, spawn, ChildProcess } from 'child_process';
import { Project, IApplication } from '../models/project.model';

const NGINX_DIR = path.resolve(__dirname, '../../../ManagerMemory/nginx');
const NGINX_CONF = path.join(NGINX_DIR, 'nginx.conf');
const DOCKER_COMPOSE = path.join(NGINX_DIR, 'docker-compose.yml');
const NGINX_PORT = 9080; // local port for nginx
const NGROK_URL = 'nonshattering-adelaida-ponchoed.ngrok-free.dev';

let ngrokProcess: ChildProcess | null = null;

export class InfrastructureService {

  /** Ensure ManagerMemory/nginx/ project exists with base files */
  ensureNginxProject(): void {
    if (!fs.existsSync(NGINX_DIR)) {
      fs.mkdirSync(NGINX_DIR, { recursive: true });
    }

    // Create Dockerfile if missing
    const dockerfile = path.join(NGINX_DIR, 'Dockerfile');
    if (!fs.existsSync(dockerfile)) {
      fs.writeFileSync(dockerfile, `FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
`, 'utf-8');
    }

    // Create docker-compose.yml if missing
    if (!fs.existsSync(DOCKER_COMPOSE)) {
      fs.writeFileSync(DOCKER_COMPOSE, this.generateDockerCompose(), 'utf-8');
    }

    // Generate initial nginx.conf
    this.regenerateNginxConf([]);
  }

  /** Regenerate nginx.conf from all company applications */
  async regenerateNginx(userId: string): Promise<{ locations: number; companies: number }> {
    this.ensureNginxProject();

    const projects = await Project.find({ userId, onHolding: { $ne: true } });
    const allApps: { companyName: string; app: IApplication }[] = [];

    for (const p of projects) {
      for (const app of (p.applications || [])) {
        allApps.push({ companyName: p.name, app });
      }
    }

    this.regenerateNginxConf(allApps);
    this.regenerateDockerCompose();

    return { locations: allApps.length, companies: projects.filter(p => (p.applications || []).length > 0).length };
  }

  /** Generate nginx.conf with path-based routing */
  private regenerateNginxConf(apps: { companyName: string; app: IApplication }[]): void {
    const locations = apps.map(({ companyName, app }) => {
      const safeName = this.slugify(companyName);
      const safeApp = this.slugify(app.name);
      const basePath = app.basePath || `/${safeName}/${safeApp}`;

      // Frontend apps need HTML5 routing support (try_files)
      if (app.type === 'frontend' || app.type === 'fullstack') {
        return `
        # ${companyName} / ${app.name} (${app.type}:${app.port})
        location ${basePath}/ {
            proxy_pass http://host.docker.internal:${app.port}/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Base-Path ${basePath};
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
        }`;
      }

      // Backend/service apps — straightforward reverse proxy
      return `
        # ${companyName} / ${app.name} (${app.type}:${app.port})
        location ${basePath}/ {
            proxy_pass http://host.docker.internal:${app.port}/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400;
        }`;
    }).join('\n');

    const conf = `# Auto-generated by ProjectsHub Infrastructure Service
# DO NOT EDIT — regenerated on every application change
# Last generated: ${new Date().toISOString()}

worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 50m;

    # Handle ngrok-skip-browser-warning
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    server {
        listen 80;
        server_name localhost ${NGROK_URL};

        # ngrok health check
        location = /health {
            return 200 'ProjectsHub Gateway OK';
            add_header Content-Type text/plain;
        }

        # Dashboard — list all registered applications
        location = / {
            default_type text/html;
            return 200 '<html><head><title>ProjectsHub Gateway</title><style>body{font-family:monospace;background:#0a0a0a;color:#d4af37;padding:2rem}h1{border-bottom:2px solid #d4af37;padding-bottom:1rem}a{color:#d4af37}</style></head><body><h1>ProjectsHub Gateway</h1><p>Active routes:</p><ul>${apps.map(({ companyName, app }) => {
              const safeName = this.slugify(companyName);
              const safeApp = this.slugify(app.name);
              const bp = app.basePath || `/${safeName}/${safeApp}`;
              return `<li><a href="${bp}/">${companyName} / ${app.name}</a> (${app.type}:${app.port})</li>`;
            }).join('')}</ul></body></html>';
        }
${locations}

        # Fallback
        location / {
            return 404 '{"error":"No application registered at this path. Check /health for available routes."}';
            add_header Content-Type application/json;
        }
    }
}
`;

    fs.writeFileSync(NGINX_CONF, conf, 'utf-8');
  }

  private generateDockerCompose(): string {
    return `# Auto-generated by ProjectsHub Infrastructure Service
version: "3.8"
services:
  gateway:
    build: .
    container_name: projectshub-gateway
    ports:
      - "${NGINX_PORT}:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
`;
  }

  private regenerateDockerCompose(): void {
    fs.writeFileSync(DOCKER_COMPOSE, this.generateDockerCompose(), 'utf-8');
  }

  /** Start the nginx gateway container */
  async startGateway(): Promise<string> {
    this.ensureNginxProject();
    return new Promise((resolve, reject) => {
      exec('docker-compose up -d --build', { cwd: NGINX_DIR }, (err, stdout, stderr) => {
        if (err) reject(new Error(`Gateway start failed: ${stderr || err.message}`));
        else resolve(`Gateway started on port ${NGINX_PORT}\n${stdout}`);
      });
    });
  }

  /** Stop the nginx gateway */
  async stopGateway(): Promise<string> {
    return new Promise((resolve, reject) => {
      exec('docker-compose down', { cwd: NGINX_DIR }, (err, stdout, stderr) => {
        if (err) reject(new Error(`Gateway stop failed: ${stderr || err.message}`));
        else resolve(`Gateway stopped\n${stdout}`);
      });
    });
  }

  /** Restart gateway (rebuild config + restart container) */
  async restartGateway(userId: string): Promise<string> {
    await this.regenerateNginx(userId);
    return new Promise((resolve, reject) => {
      exec('docker-compose up -d --build', { cwd: NGINX_DIR }, (err, stdout, stderr) => {
        if (err) reject(new Error(`Gateway restart failed: ${stderr || err.message}`));
        else resolve(`Gateway restarted on port ${NGINX_PORT}\n${stdout}`);
      });
    });
  }

  /** Reload nginx config without full restart */
  async reloadGateway(): Promise<string> {
    return new Promise((resolve, reject) => {
      exec('docker exec projectshub-gateway nginx -s reload', (err, stdout, stderr) => {
        if (err) reject(new Error(`Reload failed: ${stderr || err.message}`));
        else resolve('Nginx config reloaded');
      });
    });
  }

  /** Start ngrok tunnel pointing at the nginx gateway */
  async startNgrok(): Promise<string> {
    if (ngrokProcess) {
      return 'Ngrok is already running';
    }

    return new Promise((resolve) => {
      ngrokProcess = spawn('ngrok', ['http', String(NGINX_PORT), '--domain', NGROK_URL], {
        stdio: 'pipe',
        detached: false,
      });

      ngrokProcess.on('error', (err) => {
        ngrokProcess = null;
        resolve(`Ngrok failed to start: ${err.message}`);
      });

      ngrokProcess.on('exit', () => {
        ngrokProcess = null;
      });

      // Give it a moment to start
      setTimeout(() => {
        if (ngrokProcess) {
          resolve(`Ngrok started: https://${NGROK_URL} → localhost:${NGINX_PORT}`);
        } else {
          resolve('Ngrok process exited unexpectedly');
        }
      }, 2000);
    });
  }

  /** Stop ngrok tunnel */
  stopNgrok(): string {
    if (ngrokProcess) {
      ngrokProcess.kill();
      ngrokProcess = null;
      return 'Ngrok stopped';
    }
    return 'Ngrok was not running';
  }

  isNgrokRunning(): boolean {
    return ngrokProcess !== null;
  }

  getGatewayPort(): number {
    return NGINX_PORT;
  }

  getNgrokUrl(): string {
    return `https://${NGROK_URL}`;
  }

  /** Get the full external URL for an application */
  getAppUrl(companyName: string, appName: string, basePath?: string): string {
    const bp = basePath || `/${this.slugify(companyName)}/${this.slugify(appName)}`;
    return `https://${NGROK_URL}${bp}/`;
  }

  /** Add an application to a company */
  async addApplication(userId: string, projectId: string, app: Partial<IApplication>): Promise<IApplication> {
    const project = await Project.findOne({ _id: projectId, userId });
    if (!project) throw new Error('Company not found');

    const safeName = this.slugify(project.name);
    const safeApp = this.slugify(app.name || 'app');

    const newApp: IApplication = {
      name: app.name || 'app',
      port: app.port || 3000,
      type: app.type || 'fullstack',
      dockerService: app.dockerService || safeApp,
      command: app.command || `docker-compose up -d ${safeApp}`,
      status: 'stopped',
      tested: false,
      basePath: app.basePath || `/${safeName}/${safeApp}`,
      description: app.description || '',
      purpose: app.purpose || '',
      testInstructions: app.testInstructions || '',
      screenshots: [],
    };

    project.applications.push(newApp);
    await project.save();

    // Regenerate nginx config
    await this.regenerateNginx(userId);

    return newApp;
  }

  /** Remove an application from a company */
  async removeApplication(userId: string, projectId: string, appName: string): Promise<void> {
    const project = await Project.findOne({ _id: projectId, userId });
    if (!project) throw new Error('Company not found');

    project.applications = project.applications.filter(a => a.name !== appName);
    await project.save();

    await this.regenerateNginx(userId);
  }

  /** Update an application */
  async updateApplication(userId: string, projectId: string, appName: string, updates: Partial<IApplication>): Promise<IApplication | null> {
    const project = await Project.findOne({ _id: projectId, userId });
    if (!project) throw new Error('Company not found');

    const app = project.applications.find(a => a.name === appName);
    if (!app) throw new Error(`Application "${appName}" not found`);

    if (updates.name !== undefined) app.name = updates.name;
    if (updates.port !== undefined) app.port = updates.port;
    if (updates.type !== undefined) app.type = updates.type;
    if (updates.dockerService !== undefined) app.dockerService = updates.dockerService;
    if (updates.command !== undefined) app.command = updates.command;
    if (updates.status !== undefined) app.status = updates.status;
    if (updates.tested !== undefined) app.tested = updates.tested;
    if (updates.basePath !== undefined) app.basePath = updates.basePath;
    if (updates.description !== undefined) app.description = updates.description;
    if (updates.purpose !== undefined) app.purpose = updates.purpose;
    if (updates.testInstructions !== undefined) app.testInstructions = updates.testInstructions;

    await project.save();
    await this.regenerateNginx(userId);

    return app;
  }

  /** Get all applications across all companies */
  async getAllApplications(userId: string): Promise<{ companyName: string; companyId: string; app: IApplication }[]> {
    const projects = await Project.find({ userId });
    const result: { companyName: string; companyId: string; app: IApplication }[] = [];

    for (const p of projects) {
      for (const app of (p.applications || [])) {
        result.push({ companyName: p.name, companyId: p._id.toString(), app });
      }
    }

    return result;
  }

  /** Collect screenshots left by QA testers in .agents/screenshots/<app-name>/ and save to DB */
  async collectScreenshots(userId: string, projectId: string): Promise<number> {
    const project = await Project.findOne({ _id: projectId, userId });
    if (!project) return 0;

    const allFolders = [...(project.folders || [])];
    if (project.localPath && !allFolders.includes(project.localPath)) allFolders.unshift(project.localPath);
    const cwd = allFolders[0];
    if (!cwd) return 0;

    const screenshotsBase = path.join(cwd, '.agents', 'screenshots');
    if (!fs.existsSync(screenshotsBase)) return 0;

    const SCREENSHOTS_STORE = path.resolve(__dirname, '../../../ManagerMemory/screenshots');
    let collected = 0;

    for (const app of project.applications) {
      const appDir = path.join(screenshotsBase, app.name);
      if (!fs.existsSync(appDir)) continue;

      const files = fs.readdirSync(appDir).filter(f => /\.(png|jpg|jpeg|gif|webp)$/i.test(f));
      for (const file of files) {
        // Skip if already collected
        if (app.screenshots.some(s => s.originalName === file)) continue;

        const src = path.join(appDir, file);
        const destDir = path.join(SCREENSHOTS_STORE, projectId, app.name);
        if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });

        const destName = `${Date.now()}-${file}`;
        fs.copyFileSync(src, path.join(destDir, destName));

        app.screenshots.push({
          filename: destName,
          originalName: file,
          caption: file.replace(/\.\w+$/, '').replace(/[-_]/g, ' '),
          takenBy: 'qa-tester',
          takenAt: new Date(),
        });
        collected++;
      }
    }

    if (collected > 0) await project.save();
    return collected;
  }

  private slugify(str: string): string {
    return str.toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '');
  }
}

export const infrastructureService = new InfrastructureService();
